In [ ]:
import gmsh
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from apeGmsh import apeGmsh

from pathlib import Path

# This notebook walks through the basics of using Gmsh with Python.

In [51]:
# To check what gmsh version we are using
print("Gmsh version:", gmsh.__version__)

Gmsh version: 4.15.1

## Loading CAD models

We will first start by loading a set of elements modeled using CAD tools and exported to .IGES format.
GMSH work well with both .STEP files and .IGES files.
You can choose your prefer CAD modeling software

In [52]:
solid_CAD_file = Path(r'C:\Users\nmora\Desktop\gshTest\acad\SolidColumn')
solid_CAD_file = solid_CAD_file / 'SolidColumn_RevA.iges'

gmsh.initialize()
gmsh.model.add("SolidColumn")

# Load the IGES file using OpenCASCADE kernel (required for IGES/STEP files)
gmsh.model.occ.importShapes(str(solid_CAD_file))
gmsh.model.occ.synchronize()

print(f"Gmsh version: {gmsh.__version__}")
print(f"Loaded: {solid_CAD_file.name}")

# Launch the GUI to inspect the geometry
gmsh.fltk.run()

gmsh.finalize()

Gmsh version: 4.15.1
Loaded: SolidColumn_RevA.iges

In [ ]:
# Two ways of using either with the with block: or by manually calling initialize() and finalize()

model = apeGmsh(model_name="SolidColumn", verbose=True)
with model:
    solid_CAD_file = Path(r'C:\Users\nmora\Desktop\gshTest\acad\SolidColumn') / 'SolidColumn_RevA.iges'
    model.load_geometry_iges(solid_CAD_file)
    
    #model.launch_gui()
    #model.plot_geometry()
    
    mapping, type_summary = model.inspect.get_geometry_info()
    print(type_summary)
    print(mapping)
    
    print(mapping['points'])

Gmsh version: 4.15.1
Loaded: SolidColumn_RevA.iges

--- Global Geometry Summary ---
                          count
entity   type
curves   BSpline             36
points   Point               24
surfaces BSpline surface     14
volumes  Volume               1

--- Points Entities ---
          tag   type      x             y       z
name
Point 1     1  Point   10.0  4.700000e+01     0.0
Point 2     2  Point  190.0  4.700000e+01     0.0
Point 3     3  Point  190.0  4.700000e+01  2000.0
Point 4     4  Point   10.0  4.700000e+01  2000.0
Point 5     5  Point   10.0  3.552714e-15     0.0
Point 6     6  Point   10.0  0.000000e+00  2000.0
Point 7     7  Point    0.0  0.000000e+00     0.0
Point 8     8  Point    0.0  0.000000e+00  2000.0
Point 9     9  Point    0.0  1.000000e+02     0.0
Point 10   10  Point    0.0  1.000000e+02  2000.0
Point 11   11  Point   10.0  1.000000e+02     0.0
Point 12   12  Point   10.0  1.000000e+02  2000.0
Point 13   13  Point   10.0  5.300000e+01     0.0
Point 14   14  Point   10.0  5.300000e+01  2000.0
Point 15   15  Point  190.0  5.300000e+01     0.0
Point 16   16  Point  190.0  5.300000e+01  2000.0
Point 17   17  Point  190.0  1.000000e+02     0.0
Point 18   18  Point  190.0  1.000000e+02  2000.0
Point 19   19  Point  200.0  1.000000e+02     0.0
Point 20   20  Point  200.0  1.000000e+02  2000.0
Point 21   21  Point  200.0  0.000000e+00     0.0
Point 22   22  Point  200.0  0.000000e+00  2000.0
Point 23   23  Point  190.0  0.000000e+00     0.0
Point 24   24  Point  190.0  0.000000e+00  2000.0

--- Curves Entities ---
          tag     type  start_pt  end_pt  length  start_x       start_y  start_z  end_x         end_y   end_z  mid_x         mid_y   mid_z curvature_at_mid  u_min   u_max
name
Curve 1     1  BSpline         1       2   180.0     10.0  4.700000e+01      0.0  190.0  4.700000e+01     0.0  100.0  4.700000e+01     0.0          [1e-15]    0.0   180.0
Curve 2     2  BSpline         2       3  2000.0    190.0  4.700000e+01      0.0  190.0  4.700000e+01  2000.0  190.0  4.700000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 3     3  BSpline         3       4   180.0     10.0  4.700000e+01   2000.0  190.0  4.700000e+01  2000.0  100.0  4.700000e+01  2000.0          [1e-15]    0.0   180.0
Curve 4     4  BSpline         1       4  2000.0     10.0  4.700000e+01      0.0   10.0  4.700000e+01  2000.0   10.0  4.700000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 5     5  BSpline         1       5    47.0     10.0  3.552714e-15      0.0   10.0  4.700000e+01     0.0   10.0  2.350000e+01     0.0          [1e-15]    0.0    47.0
Curve 6     6  BSpline         4       6    47.0     10.0  3.552714e-15   2000.0   10.0  4.700000e+01  2000.0   10.0  2.350000e+01  2000.0          [1e-15]    0.0    47.0
Curve 7     7  BSpline         5       6  2000.0     10.0  3.552714e-15      0.0   10.0  3.552714e-15  2000.0   10.0  3.552714e-15  1000.0          [1e-15]    0.0  2000.0
Curve 8     8  BSpline         5       7    10.0      0.0  0.000000e+00      0.0   10.0  3.552714e-15     0.0    5.0  1.776357e-15     0.0          [1e-15]    0.0    10.0
Curve 9     9  BSpline         6       8    10.0      0.0  0.000000e+00   2000.0   10.0  3.552714e-15  2000.0    5.0  1.776357e-15  2000.0          [1e-15]    0.0    10.0
Curve 10   10  BSpline         7       8  2000.0      0.0  0.000000e+00      0.0    0.0  0.000000e+00  2000.0    0.0  0.000000e+00  1000.0          [1e-15]    0.0  2000.0
Curve 11   11  BSpline         7       9   100.0      0.0  1.000000e+02      0.0    0.0  0.000000e+00     0.0    0.0  5.000000e+01     0.0          [1e-15]    0.0   100.0
Curve 12   12  BSpline         8      10   100.0      0.0  1.000000e+02   2000.0    0.0  0.000000e+00  2000.0    0.0  5.000000e+01  2000.0          [1e-15]    0.0   100.0
Curve 13   13  BSpline         9      10  2000.0      0.0  1.000000e+02      0.0    0.0  1.000000e+02  2000.0    0.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 14   14  BSpline         9      11    10.0     10.0  1.000000e+02      0.0    0.0  1.000000e+02     0.0    5.0  1.000000e+02     0.0          [1e-15]    0.0    10.0
Curve 15   15  BSpline        10      12    10.0     10.0  1.000000e+02   2000.0    0.0  1.000000e+02  2000.0    5.0  1.000000e+02  2000.0          [1e-15]    0.0    10.0
Curve 16   16  BSpline        11      12  2000.0     10.0  1.000000e+02      0.0   10.0  1.000000e+02  2000.0   10.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 17   17  BSpline        11      13    47.0     10.0  5.300000e+01      0.0   10.0  1.000000e+02     0.0   10.0  7.650000e+01     0.0          [1e-15]    0.0    47.0
Curve 18   18  BSpline        12      14    47.0     10.0  5.300000e+01   2000.0   10.0  1.000000e+02  2000.0   10.0  7.650000e+01  2000.0          [1e-15]    0.0    47.0
Curve 19   19  BSpline        13      14  2000.0     10.0  5.300000e+01      0.0   10.0  5.300000e+01  2000.0   10.0  5.300000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 20   20  BSpline        13      15   180.0    190.0  5.300000e+01      0.0   10.0  5.300000e+01     0.0  100.0  5.300000e+01     0.0          [1e-15]    0.0   180.0
Curve 21   21  BSpline        14      16   180.0    190.0  5.300000e+01   2000.0   10.0  5.300000e+01  2000.0  100.0  5.300000e+01  2000.0          [1e-15]    0.0   180.0
Curve 22   22  BSpline        15      16  2000.0    190.0  5.300000e+01      0.0  190.0  5.300000e+01  2000.0  190.0  5.300000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 23   23  BSpline        15      17    47.0    190.0  1.000000e+02      0.0  190.0  5.300000e+01     0.0  190.0  7.650000e+01     0.0          [1e-15]    0.0    47.0
Curve 24   24  BSpline        16      18    47.0    190.0  1.000000e+02   2000.0  190.0  5.300000e+01  2000.0  190.0  7.650000e+01  2000.0          [1e-15]    0.0    47.0
Curve 25   25  BSpline        17      18  2000.0    190.0  1.000000e+02      0.0  190.0  1.000000e+02  2000.0  190.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 26   26  BSpline        17      19    10.0    200.0  1.000000e+02      0.0  190.0  1.000000e+02     0.0  195.0  1.000000e+02     0.0          [1e-15]    0.0    10.0
Curve 27   27  BSpline        18      20    10.0    200.0  1.000000e+02   2000.0  190.0  1.000000e+02  2000.0  195.0  1.000000e+02  2000.0          [1e-15]    0.0    10.0
Curve 28   28  BSpline        19      20  2000.0    200.0  1.000000e+02      0.0  200.0  1.000000e+02  2000.0  200.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 29   29  BSpline        19      21   100.0    200.0  0.000000e+00      0.0  200.0  1.000000e+02     0.0  200.0  5.000000e+01     0.0          [1e-15]    0.0   100.0
Curve 30   30  BSpline        20      22   100.0    200.0  0.000000e+00   2000.0  200.0  1.000000e+02  2000.0  200.0  5.000000e+01  2000.0          [1e-15]    0.0   100.0
Curve 31   31  BSpline        21      22  2000.0    200.0  0.000000e+00      0.0  200.0  0.000000e+00  2000.0  200.0  0.000000e+00  1000.0          [1e-15]    0.0  2000.0
Curve 32   32  BSpline        21      23    10.0    190.0  0.000000e+00      0.0  200.0  0.000000e+00     0.0  195.0  0.000000e+00     0.0          [1e-15]    0.0    10.0
Curve 33   33  BSpline        22      24    10.0    190.0  0.000000e+00   2000.0  200.0  0.000000e+00  2000.0  195.0  0.000000e+00  2000.0          [1e-15]    0.0    10.0
Curve 34   34  BSpline        23      24  2000.0    190.0  0.000000e+00      0.0  190.0  0.000000e+00  2000.0  190.0  0.000000e+00  1000.0          [1e-15]    0.0  2000.0
Curve 35   35  BSpline         2      23    47.0    190.0  4.700000e+01      0.0  190.0  0.000000e+00     0.0  190.0  2.350000e+01     0.0          [1e-15]    0.0    47.0
Curve 36   36  BSpline         3      24    47.0    190.0  4.700000e+01   2000.0  190.0  0.000000e+00  2000.0  190.0  2.350000e+01  2000.0          [1e-15]    0.0    47.0

--- Surfaces Entities ---
            tag             type  n_boundary_curves                                boundary_curves      area     cx            cy      cz            nx   ny   nz curvature_at_mid     k1     k2
name
Surface 1     1  BSpline surface                  4                                   [1, 2, 3, 4]  360000.0  100.0  4.700000e+01  1000.0  0.000000e+00 -1.0  0.0            [0.0]  [0.0]  [0.0]
Surface 2     2  BSpline surface                  4                                   [4, 5, 6, 7]   94000.0   10.0  2.350000e+01  1000.0  1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 3     3  BSpline surface                  4                                  [7, 8, 9, 10]   20000.0    5.0  1.776357e-15  1000.0  3.552714e-16 -1.0  0.0            [0.0]  [0.0]  [0.0]
Surface 4     4  BSpline surface                  4                               [10, 11, 12, 13]  200000.0    0.0  5.000000e+01  1000.0 -1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 5     5  BSpline surface                  4                               [13, 14, 15, 16]   20000.0    5.0  1.000000e+02  1000.0  0.000000e+00  1.0 -0.0            [0.0]  [0.0]  [0.0]
Surface 6     6  BSpline surface                  4                               [16, 17, 18, 19]   94000.0   10.0  7.650000e+01  1000.0  1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 7     7  BSpline surface                  4                               [19, 20, 21, 22]  360000.0  100.0  5.300000e+01  1000.0  0.000000e+00  1.0 -0.0            [0.0]  [0.0]  [0.0]
Surface 8     8  BSpline surface                  4                               [22, 23, 24, 25]   94000.0  190.0  7.650000e+01  1000.0 -1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 9     9  BSpline surface                  4                               [25, 26, 27, 28]   20000.0  195.0  1.000000e+02  1000.0  0.000000e+00  1.0 -0.0            [0.0]  [0.0]  [0.0]
Surface 10   10  BSpline surface                  4                               [28, 29, 30, 31]  200000.0  200.0  5.000000e+01  1000.0  1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 11   11  BSpline surface                  4                               [31, 32, 33, 34]   20000.0  195.0  0.000000e+00  1000.0  0.000000e+00 -1.0  0.0            [0.0]  [0.0]  [0.0]
Surface 12   12  BSpline surface                  4                                [2, 34, 35, 36]   94000.0  190.0  2.350000e+01  1000.0 -1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 13   13  BSpline surface                 12  [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36]    3080.0  100.0  5.000000e+01  2000.0  0.000000e+00 -0.0  1.0            [0.0]  [0.0]  [0.0]
Surface 14   14  BSpline surface                 12  [1, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35]    3080.0  100.0  5.000000e+01     0.0  0.000000e+00  0.0 -1.0            [0.0]  [0.0]  [0.0]

--- Volumes Entities ---
          tag    type  n_boundary_surfaces                                boundary_surfaces     volume     cx    cy      cz           ixx           iyy           izz       ixy       ixz  iyz
name
Volume 1    1  Volume                   14  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]  6160000.0  100.0  50.0  1000.0  2.056673e+12  2.095299e+12  4.530515e+10  0.000011  0.000244  0.0
                          count
entity   type
curves   BSpline             36
points   Point               24
surfaces BSpline surface     14
volumes  Volume               1
{'points': {'df':           tag   type      x             y       z
name
Point 1     1  Point   10.0  4.700000e+01     0.0
Point 2     2  Point  190.0  4.700000e+01     0.0
Point 3     3  Point  190.0  4.700000e+01  2000.0
Point 4     4  Point   10.0  4.700000e+01  2000.0
Point 5     5  Point   10.0  3.552714e-15     0.0
Point 6     6  Point   10.0  0.000000e+00  2000.0
Point 7     7  Point    0.0  0.000000e+00     0.0
Point 8     8  Point    0.0  0.000000e+00  2000.0
Point 9     9  Point    0.0  1.000000e+02     0.0
Point 10   10  Point    0.0  1.000000e+02  2000.0
Point 11   11  Point   10.0  1.000000e+02     0.0
Point 12   12  Point   10.0  1.000000e+02  2000.0
Point 13   13  Point   10.0  5.300000e+01     0.0
Point 14   14  Point   10.0  5.300000e+01  2000.0
Point 15   15  Point  190.0  5.300000e+01     0.0
Point 16   16  Point  190.0  5.300000e+01  2000.0
Point 17   17  Point  190.0  1.000000e+02     0.0
Point 18   18  Point  190.0  1.000000e+02  2000.0
Point 19   19  Point  200.0  1.000000e+02     0.0
Point 20   20  Point  200.0  1.000000e+02  2000.0
Point 21   21  Point  200.0  0.000000e+00     0.0
Point 22   22  Point  200.0  0.000000e+00  2000.0
Point 23   23  Point  190.0  0.000000e+00     0.0
Point 24   24  Point  190.0  0.000000e+00  2000.0, 'summary':        count
type
Point     24, 'entities': {1: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([10., 47.,  0.])}, 2: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([190.,  47.,   0.])}, 3: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([ 190.,   47., 2000.])}, 4: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([  10.,   47., 2000.])}, 5: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([1.00000000e+01, 3.55271368e-15, 0.00000000e+00])}, 6: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([  10.,    0., 2000.])}, 7: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([0., 0., 0.])}, 8: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([   0.,    0., 2000.])}, 9: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([  0., 100.,   0.])}, 10: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([   0.,  100., 2000.])}, 11: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([ 10., 100.,   0.])}, 12: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([  10.,  100., 2000.])}, 13: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([10., 53.,  0.])}, 14: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([  10.,   53., 2000.])}, 15: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([190.,  53.,   0.])}, 16: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([ 190.,   53., 2000.])}, 17: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([190., 100.,   0.])}, 18: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([ 190.,  100., 2000.])}, 19: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([200., 100.,   0.])}, 20: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([ 200.,  100., 2000.])}, 21: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([200.,   0.,   0.])}, 22: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([ 200.,    0., 2000.])}, 23: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([190.,   0.,   0.])}, 24: {'type': 'Point', 'boundary_tags': [], 'parametric_bounds': (array([], dtype=float64), array([], dtype=float64)), 'coords': array([ 190.,    0., 2000.])}}}, 'curves': {'df':           tag     type  start_pt  end_pt  length  start_x       start_y  \
name
Curve 1     1  BSpline         1       2   180.0     10.0  4.700000e+01
Curve 2     2  BSpline         2       3  2000.0    190.0  4.700000e+01
Curve 3     3  BSpline         3       4   180.0     10.0  4.700000e+01
Curve 4     4  BSpline         1       4  2000.0     10.0  4.700000e+01
Curve 5     5  BSpline         1       5    47.0     10.0  3.552714e-15
Curve 6     6  BSpline         4       6    47.0     10.0  3.552714e-15
Curve 7     7  BSpline         5       6  2000.0     10.0  3.552714e-15
Curve 8     8  BSpline         5       7    10.0      0.0  0.000000e+00
Curve 9     9  BSpline         6       8    10.0      0.0  0.000000e+00
Curve 10   10  BSpline         7       8  2000.0      0.0  0.000000e+00
Curve 11   11  BSpline         7       9   100.0      0.0  1.000000e+02
Curve 12   12  BSpline         8      10   100.0      0.0  1.000000e+02
Curve 13   13  BSpline         9      10  2000.0      0.0  1.000000e+02
Curve 14   14  BSpline         9      11    10.0     10.0  1.000000e+02
Curve 15   15  BSpline        10      12    10.0     10.0  1.000000e+02
Curve 16   16  BSpline        11      12  2000.0     10.0  1.000000e+02
Curve 17   17  BSpline        11      13    47.0     10.0  5.300000e+01
Curve 18   18  BSpline        12      14    47.0     10.0  5.300000e+01
Curve 19   19  BSpline        13      14  2000.0     10.0  5.300000e+01
Curve 20   20  BSpline        13      15   180.0    190.0  5.300000e+01
Curve 21   21  BSpline        14      16   180.0    190.0  5.300000e+01
Curve 22   22  BSpline        15      16  2000.0    190.0  5.300000e+01
Curve 23   23  BSpline        15      17    47.0    190.0  1.000000e+02
Curve 24   24  BSpline        16      18    47.0    190.0  1.000000e+02
Curve 25   25  BSpline        17      18  2000.0    190.0  1.000000e+02
Curve 26   26  BSpline        17      19    10.0    200.0  1.000000e+02
Curve 27   27  BSpline        18      20    10.0    200.0  1.000000e+02
Curve 28   28  BSpline        19      20  2000.0    200.0  1.000000e+02
Curve 29   29  BSpline        19      21   100.0    200.0  0.000000e+00
Curve 30   30  BSpline        20      22   100.0    200.0  0.000000e+00
Curve 31   31  BSpline        21      22  2000.0    200.0  0.000000e+00
Curve 32   32  BSpline        21      23    10.0    190.0  0.000000e+00
Curve 33   33  BSpline        22      24    10.0    190.0  0.000000e+00
Curve 34   34  BSpline        23      24  2000.0    190.0  0.000000e+00
Curve 35   35  BSpline         2      23    47.0    190.0  4.700000e+01
Curve 36   36  BSpline         3      24    47.0    190.0  4.700000e+01

          start_z  end_x         end_y   end_z  mid_x         mid_y   mid_z  \
name
Curve 1       0.0  190.0  4.700000e+01     0.0  100.0  4.700000e+01     0.0
Curve 2       0.0  190.0  4.700000e+01  2000.0  190.0  4.700000e+01  1000.0
Curve 3    2000.0  190.0  4.700000e+01  2000.0  100.0  4.700000e+01  2000.0
Curve 4       0.0   10.0  4.700000e+01  2000.0   10.0  4.700000e+01  1000.0
Curve 5       0.0   10.0  4.700000e+01     0.0   10.0  2.350000e+01     0.0
Curve 6    2000.0   10.0  4.700000e+01  2000.0   10.0  2.350000e+01  2000.0
Curve 7       0.0   10.0  3.552714e-15  2000.0   10.0  3.552714e-15  1000.0
Curve 8       0.0   10.0  3.552714e-15     0.0    5.0  1.776357e-15     0.0
Curve 9    2000.0   10.0  3.552714e-15  2000.0    5.0  1.776357e-15  2000.0

In [55]:
mapping['points']['df']

          tag   type      x             y       z
name
Point 1     1  Point   10.0  4.700000e+01     0.0
Point 2     2  Point  190.0  4.700000e+01     0.0
Point 3     3  Point  190.0  4.700000e+01  2000.0
Point 4     4  Point   10.0  4.700000e+01  2000.0
Point 5     5  Point   10.0  3.552714e-15     0.0
Point 6     6  Point   10.0  0.000000e+00  2000.0
Point 7     7  Point    0.0  0.000000e+00     0.0
Point 8     8  Point    0.0  0.000000e+00  2000.0
Point 9     9  Point    0.0  1.000000e+02     0.0
Point 10   10  Point    0.0  1.000000e+02  2000.0
Point 11   11  Point   10.0  1.000000e+02     0.0
Point 12   12  Point   10.0  1.000000e+02  2000.0
Point 13   13  Point   10.0  5.300000e+01     0.0
Point 14   14  Point   10.0  5.300000e+01  2000.0
Point 15   15  Point  190.0  5.300000e+01     0.0
Point 16   16  Point  190.0  5.300000e+01  2000.0
Point 17   17  Point  190.0  1.000000e+02     0.0
Point 18   18  Point  190.0  1.000000e+02  2000.0
Point 19   19  Point  200.0  1.000000e+02     0.0
Point 20   20  Point  200.0  1.000000e+02  2000.0
Point 21   21  Point  200.0  0.000000e+00     0.0
Point 22   22  Point  200.0  0.000000e+00  2000.0
Point 23   23  Point  190.0  0.000000e+00     0.0
Point 24   24  Point  190.0  0.000000e+00  2000.0

In [56]:
mapping['curves']['df']

,tag,type,start_pt,end_pt,length,start_x,start_y,start_z,end_x,end_y,end_z,mid_x,mid_y,mid_z,curvature_at_mid,u_min,u_max
name,,,,,,,,,,,,,,,,,
Curve 1,1,BSpline,1,2,180.0,10.0,4.700000e+01,0.0,190.0,4.700000e+01,0.0,100.0,4.700000e+01,0.0,[1e-15],0.0,180.0
Curve 2,2,BSpline,2,3,2000.0,190.0,4.700000e+01,0.0,190.0,4.700000e+01,2000.0,190.0,4.700000e+01,1000.0,[1e-15],0.0,2000.0
Curve 3,3,BSpline,3,4,180.0,10.0,4.700000e+01,2000.0,190.0,4.700000e+01,2000.0,100.0,4.700000e+01,2000.0,[1e-15],0.0,180.0
Curve 4,4,BSpline,1,4,2000.0,10.0,4.700000e+01,0.0,10.0,4.700000e+01,2000.0,10.0,4.700000e+01,1000.0,[1e-15],0.0,2000.0
Curve 5,5,BSpline,1,5,47.0,10.0,3.552714e-15,0.0,10.0,4.700000e+01,0.0,10.0,2.350000e+01,0.0,[1e-15],0.0,47.0
Curve 6,6,BSpline,4,6,47.0,10.0,3.552714e-15,2000.0,10.0,4.700000e+01,2000.0,10.0,2.350000e+01,2000.0,[1e-15],0.0,47.0
Curve 7,7,BSpline,5,6,2000.0,10.0,3.552714e-15,0.0,10.0,3.552714e-15,2000.0,10.0,3.552714e-15,1000.0,[1e-15],0.0,2000.0
Curve 8,8,BSpline,5,7,10.0,0.0,0.000000e+00,0.0,10.0,3.552714e-15,0.0,5.0,1.776357e-15,0.0,[1e-15],0.0,10.0
Curve 9,9,BSpline,6,8,10.0,0.0,0.000000e+00,2000.0,10.0,3.552714e-15,2000.0,5.0,1.776357e-15,2000.0,[1e-15],0.0,10.0
Curve 10,10,BSpline,7,8,2000.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,2000.0,0.0,0.000000e+00,1000.0,[1e-15],0.0,2000.0
Curve 11,11,BSpline,7,9,100.0,0.0,1.000000e+02,0.0,0.0,0.000000e+00,0.0,0.0,5.000000e+01,0.0,[1e-15],0.0,100.0
Curve 12,12,BSpline,8,10,100.0,0.0,1.000000e+02,2000.0,0.0,0.000000e+00,2000.0,0.0,5.000000e+01,2000.0,[1e-15],0.0,100.0
Curve 13,13,BSpline,9,10,2000.0,0.0,1.000000e+02,0.0,0.0,1.000000e+02,2000.0,0.0,1.000000e+02,1000.0,[1e-15],0.0,2000.0
Curve 14,14,BSpline,9,11,10.0,10.0,1.000000e+02,0.0,0.0,1.000000e+02,0.0,5.0,1.000000e+02,0.0,[1e-15],0.0,10.0
Curve 15,15,BSpline,10,12,10.0,10.0,1.000000e+02,2000.0,0.0,1.000000e+02,2000.0,5.0,1.000000e+02,2000.0,[1e-15],0.0,10.0
Curve 16,16,BSpline,11,12,2000.0,10.0,1.000000e+02,0.0,10.0,1.000000e+02,2000.0,10.0,1.000000e+02,1000.0,[1e-15],0.0,2000.0
Curve 17,17,BSpline,11,13,47.0,10.0,5.300000e+01,0.0,10.0,1.000000e+02,0.0,10.0,7.650000e+01,0.0,[1e-15],0.0,47.0
Curve 18,18,BSpline,12,14,47.0,10.0,5.300000e+01,2000.0,10.0,1.000000e+02,2000.0,10.0,7.650000e+01,2000.0,[1e-15],0.0,47.0
Curve 19,19,BSpline,13,14,2000.0,10.0,5.300000e+01,0.0,10.0,5.300000e+01,2000.0,10.0,5.300000e+01,1000.0,[1e-15],0.0,2000.0
Curve 20,20,BSpline,13,15,180.0,190.0,5.300000e+01,0.0,10.0,5.300000e+01,0.0,100.0,5.300000e+01,0.0,[1e-15],0.0,180.0
Curve 21,21,BSpline,14,16,180.0,190.0,5.300000e+01,2000.0,10.0,5.300000e+01,2000.0,100.0,5.300000e+01,2000.0,[1e-15],0.0,180.0
Curve 22,22,BSpline,15,16,2000.0,190.0,5.300000e+01,0.0,190.0,5.300000e+01,2000.0,190.0,5.300000e+01,1000.0,[1e-15],0.0,2000.0
Curve 23,23,BSpline,15,17,47.0,190.0,1.000000e+02,0.0,190.0,5.300000e+01,0.0,190.0,7.650000e+01,0.0,[1e-15],0.0,47.0
Curve 24,24,BSpline,16,18,47.0,190.0,1.000000e+02,2000.0,190.0,5.300000e+01,2000.0,190.0,7.650000e+01,2000.0,[1e-15],0.0,47.0
Curve 25,25,BSpline,17,18,2000.0,190.0,1.000000e+02,0.0,190.0,1.000000e+02,2000.0,190.0,1.000000e+02,1000.0,[1e-15],0.0,2000.0
Curve 26,26,BSpline,17,19,10.0,200.0,1.000000e+02,0.0,190.0,1.000000e+02,0.0,195.0,1.000000e+02,0.0,[1e-15],0.0,10.0
Curve 27,27,BSpline,18,20,10.0,200.0,1.000000e+02,2000.0,190.0,1.000000e+02,2000.0,195.0,1.000000e+02,2000.0,[1e-15],0.0,10.0
Curve 28,28,BSpline,19,20,2000.0,200.0,1.000000e+02,0.0,200.0,1.000000e+02,2000.0,200.0,1.000000e+02,1000.0,[1e-15],0.0,2000.0
Curve 29,29,BSpline,19,21,100.0,200.0,0.000000e+00,0.0,200.0,1.000000e+02,0.0,200.0,5.000000e+01,0.0,[1e-15],0.0,100.0
Curve 30,30,BSpline,20,22,100.0,200.0,0.000000e+00,2000.0,200.0,1.000000e+02,2000.0,200.0,5.000000e+01,2000.0,[1e-15],0.0,100.0
Curve 31,31,BSpline,21,22,2000.0,200.0,0.000000e+00,0.0,200.0,0.000000e+00,2000.0,200.0,0.000000e+00,1000.0,[1e-15],0.0,2000.0
Curve 32,32,BSpline,21,23,10.0,190.0,0.000000e+00,0.0,200.0,0.000000e+00,0.0,195.0,0.000000e+00,0.0,[1e-15],0.0,10.0
Curve 33,33,BSpline,22,24,10.0,190.0,0.000000e+00,2000.0,200.0,0.000000e+00,2000.0,195.0,0.000000e+00,2000.0,[1e-15],0.0,10.0
Curve 34,34,BSpline,23,24,2000.0,190.0,0.000000e+00,0.0,190.0,0.000000e+00,2000.0,190.0,0.000000e+00,1000.0,[1e-15],0.0,2000.0
Curve 35,35,BSpline,2,23,47.0,190.0,4.700000e+01,0.0,190.0,0.000000e+00,0.0,190.0,2.350000e+01,0.0,[1e-15],0.0,47.0
Curve 36,36,BSpline,3,24,47.0,190.0,4.700000e+01,2000.0,190.0,0.000000e+00,2000.0,190.0,2.350000e+01,2000.0,[1e-15],0.0,47.0

In [ ]:
from pathlib import Path

model = apeGmsh(model_name="SolidColumn", verbose=True)
model.begin()

Gmsh version: 4.15.1

In [58]:
solid_CAD_file = (
    Path(r'C:\Users\nmora\Desktop\gshTest\acad\SolidColumn')
    / 'SolidColumn_RevA.iges'
)
model.load_geometry_iges(solid_CAD_file)

Loaded: SolidColumn_RevA.iges

In [ ]:
mapping, type_summary = model.inspect.get_geometry_info()
print(type_summary)
print('------------------------------')
print(mapping['curves'])

--- Global Geometry Summary ---
                          count
entity   type
curves   BSpline             36
points   Point               24
surfaces BSpline surface     14
volumes  Volume               1

--- Points Entities ---
          tag   type      x             y       z
name
Point 1     1  Point   10.0  4.700000e+01     0.0
Point 2     2  Point  190.0  4.700000e+01     0.0
Point 3     3  Point  190.0  4.700000e+01  2000.0
Point 4     4  Point   10.0  4.700000e+01  2000.0
Point 5     5  Point   10.0  3.552714e-15     0.0
Point 6     6  Point   10.0  0.000000e+00  2000.0
Point 7     7  Point    0.0  0.000000e+00     0.0
Point 8     8  Point    0.0  0.000000e+00  2000.0
Point 9     9  Point    0.0  1.000000e+02     0.0
Point 10   10  Point    0.0  1.000000e+02  2000.0
Point 11   11  Point   10.0  1.000000e+02     0.0
Point 12   12  Point   10.0  1.000000e+02  2000.0
Point 13   13  Point   10.0  5.300000e+01     0.0
Point 14   14  Point   10.0  5.300000e+01  2000.0
Point 15   15  Point  190.0  5.300000e+01     0.0
Point 16   16  Point  190.0  5.300000e+01  2000.0
Point 17   17  Point  190.0  1.000000e+02     0.0
Point 18   18  Point  190.0  1.000000e+02  2000.0
Point 19   19  Point  200.0  1.000000e+02     0.0
Point 20   20  Point  200.0  1.000000e+02  2000.0
Point 21   21  Point  200.0  0.000000e+00     0.0
Point 22   22  Point  200.0  0.000000e+00  2000.0
Point 23   23  Point  190.0  0.000000e+00     0.0
Point 24   24  Point  190.0  0.000000e+00  2000.0

--- Curves Entities ---
          tag     type  start_pt  end_pt  length  start_x       start_y  start_z  end_x         end_y   end_z  mid_x         mid_y   mid_z curvature_at_mid  u_min   u_max
name
Curve 1     1  BSpline         1       2   180.0     10.0  4.700000e+01      0.0  190.0  4.700000e+01     0.0  100.0  4.700000e+01     0.0          [1e-15]    0.0   180.0
Curve 2     2  BSpline         2       3  2000.0    190.0  4.700000e+01      0.0  190.0  4.700000e+01  2000.0  190.0  4.700000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 3     3  BSpline         3       4   180.0     10.0  4.700000e+01   2000.0  190.0  4.700000e+01  2000.0  100.0  4.700000e+01  2000.0          [1e-15]    0.0   180.0
Curve 4     4  BSpline         1       4  2000.0     10.0  4.700000e+01      0.0   10.0  4.700000e+01  2000.0   10.0  4.700000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 5     5  BSpline         1       5    47.0     10.0  3.552714e-15      0.0   10.0  4.700000e+01     0.0   10.0  2.350000e+01     0.0          [1e-15]    0.0    47.0
Curve 6     6  BSpline         4       6    47.0     10.0  3.552714e-15   2000.0   10.0  4.700000e+01  2000.0   10.0  2.350000e+01  2000.0          [1e-15]    0.0    47.0
Curve 7     7  BSpline         5       6  2000.0     10.0  3.552714e-15      0.0   10.0  3.552714e-15  2000.0   10.0  3.552714e-15  1000.0          [1e-15]    0.0  2000.0
Curve 8     8  BSpline         5       7    10.0      0.0  0.000000e+00      0.0   10.0  3.552714e-15     0.0    5.0  1.776357e-15     0.0          [1e-15]    0.0    10.0
Curve 9     9  BSpline         6       8    10.0      0.0  0.000000e+00   2000.0   10.0  3.552714e-15  2000.0    5.0  1.776357e-15  2000.0          [1e-15]    0.0    10.0
Curve 10   10  BSpline         7       8  2000.0      0.0  0.000000e+00      0.0    0.0  0.000000e+00  2000.0    0.0  0.000000e+00  1000.0          [1e-15]    0.0  2000.0
Curve 11   11  BSpline         7       9   100.0      0.0  1.000000e+02      0.0    0.0  0.000000e+00     0.0    0.0  5.000000e+01     0.0          [1e-15]    0.0   100.0
Curve 12   12  BSpline         8      10   100.0      0.0  1.000000e+02   2000.0    0.0  0.000000e+00  2000.0    0.0  5.000000e+01  2000.0          [1e-15]    0.0   100.0
Curve 13   13  BSpline         9      10  2000.0      0.0  1.000000e+02      0.0    0.0  1.000000e+02  2000.0    0.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 14   14  BSpline         9      11    10.0     10.0  1.000000e+02      0.0    0.0  1.000000e+02     0.0    5.0  1.000000e+02     0.0          [1e-15]    0.0    10.0
Curve 15   15  BSpline        10      12    10.0     10.0  1.000000e+02   2000.0    0.0  1.000000e+02  2000.0    5.0  1.000000e+02  2000.0          [1e-15]    0.0    10.0
Curve 16   16  BSpline        11      12  2000.0     10.0  1.000000e+02      0.0   10.0  1.000000e+02  2000.0   10.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 17   17  BSpline        11      13    47.0     10.0  5.300000e+01      0.0   10.0  1.000000e+02     0.0   10.0  7.650000e+01     0.0          [1e-15]    0.0    47.0
Curve 18   18  BSpline        12      14    47.0     10.0  5.300000e+01   2000.0   10.0  1.000000e+02  2000.0   10.0  7.650000e+01  2000.0          [1e-15]    0.0    47.0
Curve 19   19  BSpline        13      14  2000.0     10.0  5.300000e+01      0.0   10.0  5.300000e+01  2000.0   10.0  5.300000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 20   20  BSpline        13      15   180.0    190.0  5.300000e+01      0.0   10.0  5.300000e+01     0.0  100.0  5.300000e+01     0.0          [1e-15]    0.0   180.0
Curve 21   21  BSpline        14      16   180.0    190.0  5.300000e+01   2000.0   10.0  5.300000e+01  2000.0  100.0  5.300000e+01  2000.0          [1e-15]    0.0   180.0
Curve 22   22  BSpline        15      16  2000.0    190.0  5.300000e+01      0.0  190.0  5.300000e+01  2000.0  190.0  5.300000e+01  1000.0          [1e-15]    0.0  2000.0
Curve 23   23  BSpline        15      17    47.0    190.0  1.000000e+02      0.0  190.0  5.300000e+01     0.0  190.0  7.650000e+01     0.0          [1e-15]    0.0    47.0
Curve 24   24  BSpline        16      18    47.0    190.0  1.000000e+02   2000.0  190.0  5.300000e+01  2000.0  190.0  7.650000e+01  2000.0          [1e-15]    0.0    47.0
Curve 25   25  BSpline        17      18  2000.0    190.0  1.000000e+02      0.0  190.0  1.000000e+02  2000.0  190.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 26   26  BSpline        17      19    10.0    200.0  1.000000e+02      0.0  190.0  1.000000e+02     0.0  195.0  1.000000e+02     0.0          [1e-15]    0.0    10.0
Curve 27   27  BSpline        18      20    10.0    200.0  1.000000e+02   2000.0  190.0  1.000000e+02  2000.0  195.0  1.000000e+02  2000.0          [1e-15]    0.0    10.0
Curve 28   28  BSpline        19      20  2000.0    200.0  1.000000e+02      0.0  200.0  1.000000e+02  2000.0  200.0  1.000000e+02  1000.0          [1e-15]    0.0  2000.0
Curve 29   29  BSpline        19      21   100.0    200.0  0.000000e+00      0.0  200.0  1.000000e+02     0.0  200.0  5.000000e+01     0.0          [1e-15]    0.0   100.0
Curve 30   30  BSpline        20      22   100.0    200.0  0.000000e+00   2000.0  200.0  1.000000e+02  2000.0  200.0  5.000000e+01  2000.0          [1e-15]    0.0   100.0
Curve 31   31  BSpline        21      22  2000.0    200.0  0.000000e+00      0.0  200.0  0.000000e+00  2000.0  200.0  0.000000e+00  1000.0          [1e-15]    0.0  2000.0
Curve 32   32  BSpline        21      23    10.0    190.0  0.000000e+00      0.0  200.0  0.000000e+00     0.0  195.0  0.000000e+00     0.0          [1e-15]    0.0    10.0
Curve 33   33  BSpline        22      24    10.0    190.0  0.000000e+00   2000.0  200.0  0.000000e+00  2000.0  195.0  0.000000e+00  2000.0          [1e-15]    0.0    10.0
Curve 34   34  BSpline        23      24  2000.0    190.0  0.000000e+00      0.0  190.0  0.000000e+00  2000.0  190.0  0.000000e+00  1000.0          [1e-15]    0.0  2000.0
Curve 35   35  BSpline         2      23    47.0    190.0  4.700000e+01      0.0  190.0  0.000000e+00     0.0  190.0  2.350000e+01     0.0          [1e-15]    0.0    47.0
Curve 36   36  BSpline         3      24    47.0    190.0  4.700000e+01   2000.0  190.0  0.000000e+00  2000.0  190.0  2.350000e+01  2000.0          [1e-15]    0.0    47.0

--- Surfaces Entities ---
            tag             type  n_boundary_curves                                boundary_curves      area     cx            cy      cz            nx   ny   nz curvature_at_mid     k1     k2
name
Surface 1     1  BSpline surface                  4                                   [1, 2, 3, 4]  360000.0  100.0  4.700000e+01  1000.0  0.000000e+00 -1.0  0.0            [0.0]  [0.0]  [0.0]
Surface 2     2  BSpline surface                  4                                   [4, 5, 6, 7]   94000.0   10.0  2.350000e+01  1000.0  1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 3     3  BSpline surface                  4                                  [7, 8, 9, 10]   20000.0    5.0  1.776357e-15  1000.0  3.552714e-16 -1.0  0.0            [0.0]  [0.0]  [0.0]
Surface 4     4  BSpline surface                  4                               [10, 11, 12, 13]  200000.0    0.0  5.000000e+01  1000.0 -1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 5     5  BSpline surface                  4                               [13, 14, 15, 16]   20000.0    5.0  1.000000e+02  1000.0  0.000000e+00  1.0 -0.0            [0.0]  [0.0]  [0.0]
Surface 6     6  BSpline surface                  4                               [16, 17, 18, 19]   94000.0   10.0  7.650000e+01  1000.0  1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 7     7  BSpline surface                  4                               [19, 20, 21, 22]  360000.0  100.0  5.300000e+01  1000.0  0.000000e+00  1.0 -0.0            [0.0]  [0.0]  [0.0]
Surface 8     8  BSpline surface                  4                               [22, 23, 24, 25]   94000.0  190.0  7.650000e+01  1000.0 -1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 9     9  BSpline surface                  4                               [25, 26, 27, 28]   20000.0  195.0  1.000000e+02  1000.0  0.000000e+00  1.0 -0.0            [0.0]  [0.0]  [0.0]
Surface 10   10  BSpline surface                  4                               [28, 29, 30, 31]  200000.0  200.0  5.000000e+01  1000.0  1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 11   11  BSpline surface                  4                               [31, 32, 33, 34]   20000.0  195.0  0.000000e+00  1000.0  0.000000e+00 -1.0  0.0            [0.0]  [0.0]  [0.0]
Surface 12   12  BSpline surface                  4                                [2, 34, 35, 36]   94000.0  190.0  2.350000e+01  1000.0 -1.000000e+00 -0.0  0.0            [0.0]  [0.0]  [0.0]
Surface 13   13  BSpline surface                 12  [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36]    3080.0  100.0  5.000000e+01  2000.0  0.000000e+00 -0.0  1.0            [0.0]  [0.0]  [0.0]
Surface 14   14  BSpline surface                 12  [1, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35]    3080.0  100.0  5.000000e+01     0.0  0.000000e+00  0.0 -1.0            [0.0]  [0.0]  [0.0]

--- Volumes Entities ---
          tag    type  n_boundary_surfaces                                boundary_surfaces     volume     cx    cy      cz           ixx           iyy           izz       ixy       ixz  iyz
name
Volume 1    1  Volume                   14  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]  6160000.0  100.0  50.0  1000.0  2.056673e+12  2.095299e+12  4.530515e+10  0.000011  0.000244  0.0
                          count
entity   type
curves   BSpline             36
points   Point               24
surfaces BSpline surface     14
volumes  Volume               1
------------------------------
{'df':           tag     type  start_pt  end_pt  length  start_x       start_y  \
name
Curve 1     1  BSpline         1       2   180.0     10.0  4.700000e+01
Curve 2     2  BSpline         2       3  2000.0    190.0  4.700000e+01
Curve 3     3  BSpline         3       4   180.0     10.0  4.700000e+01
Curve 4     4  BSpline         1       4  2000.0     10.0  4.700000e+01
Curve 5     5  BSpline         1       5    47.0     10.0  3.552714e-15
Curve 6     6  BSpline         4       6    47.0     10.0  3.552714e-15
Curve 7     7  BSpline         5       6  2000.0     10.0  3.552714e-15
Curve 8     8  BSpline         5       7    10.0      0.0  0.000000e+00
Curve 9     9  BSpline         6       8    10.0      0.0  0.000000e+00
Curve 10   10  BSpline         7       8  2000.0      0.0  0.000000e+00
Curve 11   11  BSpline         7       9   100.0      0.0  1.000000e+02
Curve 12   12  BSpline         8      10   100.0      0.0  1.000000e+02
Curve 13   13  BSpline         9      10  2000.0      0.0  1.000000e+02
Curve 14   14  BSpline         9      11    10.0     10.0  1.000000e+02
Curve 15   15  BSpline        10      12    10.0     10.0  1.000000e+02
Curve 16   16  BSpline        11      12  2000.0     10.0  1.000000e+02
Curve 17   17  BSpline        11      13    47.0     10.0  5.300000e+01
Curve 18   18  BSpline        12      14    47.0     10.0  5.300000e+01
Curve 19   19  BSpline        13      14  2000.0     10.0  5.300000e+01
Curve 20   20  BSpline        13      15   180.0    190.0  5.300000e+01
Curve 21   21  BSpline        14      16   180.0    190.0  5.300000e+01
Curve 22   22  BSpline        15      16  2000.0    190.0  5.300000e+01
Curve 23   23  BSpline        15      17    47.0    190.0  1.000000e+02
Curve 24   24  BSpline        16      18    47.0    190.0  1.000000e+02
Curve 25   25  BSpline        17      18  2000.0    190.0  1.000000e+02
Curve 26   26  BSpline        17      19    10.0    200.0  1.000000e+02
Curve 27   27  BSpline        18      20    10.0    200.0  1.000000e+02
Curve 28   28  BSpline        19      20  2000.0    200.0  1.000000e+02
Curve 29   29  BSpline        19      21   100.0    200.0  0.000000e+00
Curve 30   30  BSpline        20      22   100.0    200.0  0.000000e+00
Curve 31   31  BSpline        21      22  2000.0    200.0  0.000000e+00
Curve 32   32  BSpline        21      23    10.0    190.0  0.000000e+00
Curve 33   33  BSpline        22      24    10.0    190.0  0.000000e+00
Curve 34   34  BSpline        23      24  2000.0    190.0  0.000000e+00
Curve 35   35  BSpline         2      23    47.0    190.0  4.700000e+01
Curve 36   36  BSpline         3      24    47.0    190.0  4.700000e+01

          start_z  end_x         end_y   end_z  mid_x         mid_y   mid_z  \
name
Curve 1       0.0  190.0  4.700000e+01     0.0  100.0  4.700000e+01     0.0
Curve 2       0.0  190.0  4.700000e+01  2000.0  190.0  4.700000e+01  1000.0
Curve 3    2000.0  190.0  4.700000e+01  2000.0  100.0  4.700000e+01  2000.0
Curve 4       0.0   10.0  4.700000e+01  2000.0   10.0  4.700000e+01  1000.0
Curve 5       0.0   10.0  4.700000e+01     0.0   10.0  2.350000e+01     0.0
Curve 6    2000.0   10.0  4.700000e+01  2000.0   10.0  2.350000e+01  2000.0
Curve 7       0.0   10.0  3.552714e-15  2000.0   10.0  3.552714e-15  1000.0
Curve 8       0.0   10.0  3.552714e-15     0.0    5.0  1.776357e-15     0.0
Curve 9    2000.0   10.0  3.552714e-15  2000.0    5.0  1.776357e-15  2000.0
Curve 10      0.0    0.0  0.000000e+00  2000.0    0.0  0.000000e+00  1000.0
Curve 11      0.0    0.0  0.000000e+00     0.0    0.0  5.000000e+01     0.0
Curve 12   2000.0    0.0  0.000000e+00  2000.0    0.0  5.000000e+01  2000.0
Curve 13      0.0    0.0  1.000000e+02  2000.0    0.0  1.000000e+02  1000.0
Curve 14      0.0    0.0  1.000000e+02     0.0    5.0  1.000000e+02     0.0
Curve 15   2000.0    0.0  1.000000e+02  2000.0    5.0  1.000000e+02  2000.0
Curve 16      0.0   10.0  1.000000e+02  2000.0   10.0  1.000000e+02  1000.0
Curve 17      0.0   10.0  1.000000e+02     0.0   10.0  7.650000e+01     0.0
Curve 18   2000.0   10.0  1.000000e+02  2000.0   10.0  7.650000e+01  2000.0
Curve 19      0.0   10.0  5.300000e+01  2000.0   10.0  5.300000e+01  1000.0
Curve 20      0.0   10.0  5.300000e+01     0.0  100.0  5.300000e+01     0.0
Curve 21   2000.0   10.0  5.300000e+01  2000.0  100.0  5.300000e+01  2000.0
Curve 22      0.0  190.0  5.300000e+01  2000.0  190.0  5.300000e+01  1000.0
Curve 23      0.0  190.0  5.300000e+01     0.0  190.0  7.650000e+01     0.0
Curve 24   2000.0  190.0  5.300000e+01  2000.0  190.0  7.650000e+01  2000.0
Curve 25      0.0  190.0  1.000000e+02  2000.0  190.0  1.000000e+02  1000.0
Curve 26      0.0  190.0  1.000000e+02     0.0  195.0  1.000000e+02     0.0
Curve 27   2000.0  190.0  1.000000e+02  2000.0  195.0  1.000000e+02  2000.0
Curve 28      0.0  200.0  1.000000e+02  2000.0  200.0  1.000000e+02  1000.0
Curve 29      0.0  200.0  1.000000e+02     0.0  200.0  5.000000e+01     0.0
Curve 30   2000.0  200.0  1.000000e+02  2000.0  200.0  5.000000e+01  2000.0
Curve 31      0.0  200.0  0.000000e+00  2000.0  200.0  0.000000e+00  1000.0
Curve 32      0.0  200.0  0.000000e+00     0.0  195.0  0.000000e+00     0.0
Curve 33   2000.0  200.0  0.000000e+00  2000.0  195.0  0.000000e+00  2000.0
Curve 34      0.0  190.0  0.000000e+00  2000.0  190.0  0.000000e+00  1000.0
Curve 35      0.0  190.0  0.000000e+00     0.0  190.0  2.350000e+01     0.0
Curve 36   2000.0  190.0  0.000000e+00  2000.0  190.0  2.350000e+01  2000.0

         curvature_at_mid  u_min   u_max
name
Curve 1           [1e-15]    0.0   180.0
Curve 2           [1e-15]    0.0  2000.0
Curve 3           [1e-15]    0.0   180.0
Curve 4           [1e-15]    0.0  2000.0
Curve 5           [1e-15]    0.0    47.0
Curve 6           [1e-15]    0.0    47.0
Curve 7           [1e-15]    0.0  2000.0
Curve 8           [1e-15]    0.0    10.0
Curve 9           [1e-15]    0.0    10.0
Curve 10          [1e-15]    0.0  2000.0
Curve 11          [1e-15]    0.0   100.0
Curve 12          [1e-15]    0.0   100.0
Curve 13          [1e-15]    0.0  2000.0
Curve 14          [1e-15]    0.0    10.0
Curve 15          [1e-15]    0.0    10.0
Curve 16          [1e-15]    0.0  2000.0
Curve 17          [1e-15]    0.0    47.0
Curve 18          [1e-15]    0.0    47.0
Curve 19          [1e-15]    0.0  2000.0
Curve 20          [1e-15]    0.0   180.0
Curve 21          [1e-15]    0.0   180.0
Curve 22          [1e-15]    0.0  2000.0
Curve 23          [1e-15]    0.0    47.0
Curve 24          [1e-15]    0.0    47.0
Curve 25          [1e-15]    0.0  2000.0
Curve 26          [1e-15]    0.0    10.0
Curve 27          [1e-15]    0.0    10.0
Curve 28          [1e-15]    0.0  2000.0
Curve 29          [1e-15]    0.0   100.0
Curve 30          [1e-15]    0.0   100.0
Curve 31          [1e-15]    0.0  2000.0
Curve 32          [1e-15]    0.0    10.0
Curve 33          [1e-15]    0.0    10.0
Curve 34          [1e-15]    0.0  2000.0
Curve 35          [1e-15]    0.0    47.0
Curve 36          [1e-15]    0.0    47.0  , 'summary':          count
type

In [60]:
model.inspect_entity(
    dim=1,  # curves
    tag=1   # first curve tag
)

--- Entity (dim=1, tag=1) ---
  dim                      : 1
  tag                      : 1
  type                     : BSpline
  boundary_tags            : [1, 2]
  parametric_bounds        : (array([0.]), array([180.]))
  length                   : 180.0
  start                    : [10. 47.  0.]
  end                      : [190.  47.   0.]
  midpoint                 : [100.  47.   0.]
  curvature_at_mid         : [1.e-15]

{'dim': 1,
 'tag': 1,
 'type': 'BSpline',
 'boundary_tags': [1, 2],
 'parametric_bounds': (array([0.]), array([180.])),
 'length': 180.0,
 'start': array([10., 47.,  0.]),
 'end': array([190.,  47.,   0.]),
 'midpoint': array([100.,  47.,   0.]),
 'curvature_at_mid': array([1.e-15])}

In [61]:
model.end()